# Generated by Django 6.0.2 on 2026-02-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(max_length=255)),
                ('height', models.IntegerField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('photographer', models.CharField(max_length=255)),
                ('photographer_url', models.CharField(max_length=255)),
                ('photographer_id', models.CharField(max_length=255)),
                ('avg_color', models.CharField(max_length=255)),
                ('original', models.CharField(max_length=255)),
                ('large2x', models.CharField(max_length=255)),
                ('large', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=255)),
                ('small', models.CharField(max_length=255)),
                ('portrait', models.CharField(max_length=255)),
                ('landscape', models.CharField(max_length=255)),
                ('tiny', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
    ]
