# Generated by Django 6.0.2 on 2026-02-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(),
        ),
    ]
