# Generated by Django 6.0.2 on 2026-02-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_height_alter_photo_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photographer_id',
            field=models.IntegerField(),
        ),
    ]
